#!/usr/bin/env python3
"""Ratchet gate for mypy: block *new* type errors without demanding a clean slate.

Why this exists
---------------
`mypy blast_ocr/` currently reports 130 errors across 28 files. Two obvious
options were both wrong:

  * Hard-gate on zero errors -- fails wall-to-wall on day one, so it gets
    reverted or `|| true`-d within a week (which is exactly what ci.yml did).
  * `mypy ... || true` -- the job is green whatever mypy says, so a genuinely
    new type error introduced today is indistinguishable from the 130 that
    were already there. That is not a gate, it is a decoration.

The ratchet is the third option: record the *current* findings as a baseline,
then fail CI only when a finding appears that is not in that baseline. The
existing debt stays parked, new debt cannot land, and the baseline can only
be moved backwards deliberately (`--update-baseline`, which is a reviewable
diff in the PR).

Baseline granularity
--------------------
Findings are keyed on ``<file>::<error-code>`` and counted, deliberately
*excluding* the line number. Including line numbers would make the baseline
churn on every unrelated edit above a finding; counting per (file, code) pair
still catches "fixed one error and introduced another one somewhere else",
which a plain total-count baseline would silently pass.

Usage
-----
    python scripts/ci_mypy_gate.py blast_ocr/                 # check (CI)
    python scripts/ci_mypy_gate.py blast_ocr/ --update-baseline
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BASELINE = REPO_ROOT / ".github" / "baselines" / "mypy.json"

# mypy's default output line, e.g.
#   blast_ocr/ui/web_app.py:405: error: Incompatible types ...  [assignment]
# Notes ("note:") and summary lines are ignored -- only `error:` counts.
_ERROR_RE = re.compile(
    r"^(?P<file>[^:]+):(?P<line>\d+):(?:\d+:)?\s+error:\s+(?P<msg>.*?)(?:\s+\[(?P<code>[\w-]+)\])?$"
)


def run_mypy(targets: list[str]) -> tuple[str, int]:
    """Run mypy and return (combined output, exit code).

    mypy exits 1 when it finds errors and 2 on a *usage/internal* failure.
    Only the former is data we can ratchet against; the latter has to fail
    the job loudly rather than being silently read as "no findings".
    """
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", *targets],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    return proc.stdout + proc.stderr, proc.returncode


def parse_findings(output: str) -> Counter[str]:
    findings: Counter[str] = Counter()
    for raw in output.splitlines():
        match = _ERROR_RE.match(raw.strip())
        if not match:
            continue
        # Normalise to forward slashes so a baseline recorded on Linux still
        # matches a developer running the same gate on Windows.
        path = match.group("file").replace("\\", "/")
        code = match.group("code") or "no-code"
        findings[f"{path}::{code}"] += 1
    return findings


def load_baseline(path: Path) -> Counter[str]:
    if not path.exists():
        return Counter()
    data = json.loads(path.read_text(encoding="utf-8"))
    return Counter(data.get("findings", {}))


def save_baseline(path: Path, findings: Counter[str], total: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "_comment": (
            "Generated by scripts/ci_mypy_gate.py --update-baseline. "
            "Each key is '<file>::<mypy-error-code>' and the value is how many "
            "such errors that file currently has. CI fails if any count rises "
            "or a new key appears. Lower these numbers as debt is paid off; "
            "never raise them to make a failing build pass."
        ),
        "total_errors": total,
        "findings": dict(sorted(findings.items())),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_summary(lines: list[str]) -> None:
    """Append a markdown block to the GitHub Actions step summary, if present.

    This is the half that `|| true` threw away: even when the gate passes,
    the findings stay visible on the run page instead of being buried in a
    collapsed log nobody opens.
    """
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return
    with open(summary_path, "a", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("targets", nargs="*", default=["blast_ocr/"])
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help="Rewrite the baseline from the current findings instead of checking.",
    )
    args = parser.parse_args()
    targets = args.targets or ["blast_ocr/"]

    output, code = run_mypy(targets)
    if code not in (0, 1):
        print(output)
        print(f"::error::mypy exited {code} (usage or internal error, not a finding count)")
        return code

    findings = parse_findings(output)
    total = sum(findings.values())

    if args.update_baseline:
        save_baseline(args.baseline, findings, total)
        print(f"Baseline written to {args.baseline}: {total} errors across {len(findings)} keys.")
        return 0

    baseline = load_baseline(args.baseline)
    regressions = {
        key: (count, baseline.get(key, 0))
        for key, count in findings.items()
        if count > baseline.get(key, 0)
    }
    improvements = {
        key: (findings.get(key, 0), count)
        for key, count in baseline.items()
        if findings.get(key, 0) < count
    }

    baseline_total = sum(baseline.values())
    summary = [
        "## mypy ratchet",
        "",
        f"- Baseline: **{baseline_total}** errors",
        f"- This run: **{total}** errors",
        f"- New/increased findings: **{len(regressions)}**",
        "",
    ]

    if regressions:
        summary.append("### New type errors (blocking)")
        summary.append("")
        summary.append("| file::code | baseline | now |")
        summary.append("| --- | --- | --- |")
        for key, (now, was) in sorted(regressions.items()):
            summary.append(f"| `{key}` | {was} | {now} |")
        summary.append("")
        write_summary(summary)

        print(output)
        print("\n" + "=" * 72)
        print("mypy ratchet FAILED -- these findings are not in the baseline:")
        for key, (now, was) in sorted(regressions.items()):
            print(f"  {key}: {was} -> {now}")
        print(
            "\nFix the new errors, or -- if they are genuinely pre-existing debt this\n"
            "gate is only now seeing -- run:\n"
            "    python scripts/ci_mypy_gate.py blast_ocr/ --update-baseline\n"
            "and commit the baseline diff so the increase is reviewed, not silent."
        )
        return 1

    if improvements:
        summary.append("### Fixed since the baseline :tada:")
        summary.append("")
        for key, (now, was) in sorted(improvements.items()):
            summary.append(f"- `{key}`: {was} → {now}")
        summary.append("")
        summary.append(
            "_Run `python scripts/ci_mypy_gate.py blast_ocr/ --update-baseline` "
            "to lock these in._"
        )
        summary.append("")

    write_summary(summary)
    print(f"mypy ratchet OK: {total} errors, none new versus the {baseline_total}-error baseline.")
    if improvements:
        print(f"{len(improvements)} finding group(s) improved -- consider updating the baseline.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
