#!/usr/bin/env python3
"""Ratchet gate for pip-audit: block *newly disclosed* CVEs, surface the rest.

Why this exists
---------------
`pip-audit -r requirements.txt -r requirements-production.txt` currently
reports 28 known vulnerabilities across 4 packages (streamlit 1.32.0,
pillow 10.4.0, protobuf 4.25.9, starlette 0.38.6). Every one of them traces
back to the same deliberate stability pins documented in docs/adr/0013:
streamlit is pinned to 1.32.0 for the Streamlit Community Cloud deployment,
which drags protobuf<5 and (via the wider resolve) an older pillow with it;
starlette 0.38.6 comes in transitively via requirements-production.txt's
`fastapi<0.113.0`, itself pinned to stay compatible with pydantic==2.6.3.
Upgrading to clear the audit is a real project, not a CI flag.

So `pip-audit ... || true` was the honest short-term call -- but it means a
CVE disclosed *tomorrow*, in a dependency we could trivially bump, lands
just as silently as the 28 we have consciously accepted. This gate splits
those two cases apart:

  * Vulnerabilities recorded in the baseline are accepted risk. Reported on
    the run summary so they stay visible, but not blocking.
  * Anything not in the baseline fails the job. Either bump the dependency,
    or add it to the baseline in a reviewable commit that says why.

Baseline granularity
--------------------
Keyed on ``<package>::<vuln-id>``, deliberately *without* the installed
version: when a pin moves, the vulnerabilities it fixes drop out (reported as
an improvement) and any the new version introduces are unrecognised, and so
correctly blocking.

Usage
-----
    python scripts/ci_pip_audit_gate.py -r requirements.txt -r requirements-production.txt
    python scripts/ci_pip_audit_gate.py -r requirements.txt --update-baseline
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BASELINE = REPO_ROOT / ".github" / "baselines" / "pip-audit.json"


def run_pip_audit(requirements: list[Path]) -> dict[str, dict]:
    """Audit each requirements file, returning {package::vuln_id: detail}.

    pip-audit exits 1 when it finds vulnerabilities and non-0/1 when the audit
    itself fails (network, unresolvable requirements). The latter must fail the
    job rather than being read as "clean" -- the whole point of this rewrite is
    that a broken check is never silently a passing check.
    """
    findings: dict[str, dict] = {}
    for req in requirements:
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "pip_audit",
                "-r",
                str(req),
                "--format",
                "json",
                "--progress-spinner",
                "off",
            ],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
        )
        if proc.returncode not in (0, 1) or not proc.stdout.strip():
            print(proc.stdout)
            print(proc.stderr, file=sys.stderr)
            raise SystemExit(
                f"::error::pip-audit failed to audit {req} (exit {proc.returncode}). "
                "Treating this as a hard failure rather than as 'no vulnerabilities'."
            )
        report = json.loads(proc.stdout)
        for dep in report.get("dependencies", []):
            for vuln in dep.get("vulns", []):
                key = f"{dep['name']}::{vuln['id']}"
                # A package audited from two requirements files reports the same
                # finding twice; keep one entry, preferring whichever record
                # already carries a fix version.
                if key not in findings or not findings[key].get("fix_versions"):
                    findings[key] = {
                        "package": dep["name"],
                        "version": dep.get("version", ""),
                        "id": vuln["id"],
                        "fix_versions": vuln.get("fix_versions", []),
                        "requirements_file": req.name,
                    }
    return findings


def load_baseline(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8")).get("accepted", {})


def save_baseline(path: Path, findings: dict[str, dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "_comment": (
            "Known-and-accepted dependency vulnerabilities, generated by "
            "scripts/ci_pip_audit_gate.py --update-baseline. Every entry here is a "
            "CVE we are knowingly shipping because the pin that causes it is "
            "load-bearing (see docs/adr/0013 and the header of requirements.txt). "
            "CI fails on any vulnerability NOT listed here. Adding an entry is a "
            "deliberate, reviewable risk acceptance -- not a way to quiet the build."
        ),
        "accepted": dict(sorted(findings.items())),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_summary(lines: list[str]) -> None:
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return
    with open(summary_path, "a", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-r",
        "--requirement",
        dest="requirements",
        action="append",
        type=Path,
        default=None,
        help="Requirements file to audit (repeatable).",
    )
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument("--update-baseline", action="store_true")
    args = parser.parse_args()
    requirements = args.requirements or [REPO_ROOT / "requirements.txt"]

    findings = run_pip_audit(requirements)

    if args.update_baseline:
        save_baseline(args.baseline, findings)
        print(f"Baseline written to {args.baseline}: {len(findings)} accepted vulnerabilities.")
        return 0

    baseline = load_baseline(args.baseline)
    new = {k: v for k, v in findings.items() if k not in baseline}
    resolved = sorted(set(baseline) - set(findings))

    summary = [
        "## Dependency vulnerability ratchet (pip-audit)",
        "",
        f"- Accepted in baseline: **{len(baseline)}**",
        f"- Found this run: **{len(findings)}**",
        f"- New (blocking): **{len(new)}**",
        "",
    ]

    if new:
        summary.append("### New vulnerabilities (blocking)")
        summary.append("")
        summary.append("| package | installed | advisory | fixed in |")
        summary.append("| --- | --- | --- | --- |")
        for key in sorted(new):
            v = new[key]
            fix = ", ".join(v["fix_versions"]) or "_no fix released_"
            summary.append(f"| `{v['package']}` | {v['version']} | {v['id']} | {fix} |")
        summary.append("")
        write_summary(summary)

        print("pip-audit ratchet FAILED -- vulnerabilities not in the accepted baseline:")
        for key in sorted(new):
            v = new[key]
            fix = ", ".join(v["fix_versions"]) or "no fix released"
            print(f"  {v['package']} {v['version']}: {v['id']} (fixed in: {fix})")
        print(
            "\nEither bump the dependency, or -- if the pin is load-bearing -- run:\n"
            "    python scripts/ci_pip_audit_gate.py -r requirements.txt "
            "-r requirements-production.txt --update-baseline\n"
            "and commit the baseline diff with a note on why the risk is accepted."
        )
        return 1

    if resolved:
        summary.append("### Resolved since the baseline :tada:")
        summary.append("")
        for key in resolved:
            summary.append(f"- `{key}`")
        summary.append("")
        summary.append(
            "_Run `scripts/ci_pip_audit_gate.py ... --update-baseline` to drop these._"
        )
        summary.append("")

    if findings:
        summary.append("<details><summary>Accepted vulnerabilities still present</summary>")
        summary.append("")
        summary.append("| package | installed | advisory | fixed in |")
        summary.append("| --- | --- | --- | --- |")
        for key in sorted(findings):
            v = findings[key]
            fix = ", ".join(v["fix_versions"]) or "_no fix released_"
            summary.append(f"| `{v['package']}` | {v['version']} | {v['id']} | {fix} |")
        summary.append("")
        summary.append("</details>")
        summary.append("")

    write_summary(summary)
    print(
        f"pip-audit ratchet OK: {len(findings)} known vulnerabilities, "
        f"all present in the accepted baseline ({len(baseline)} entries)."
    )
    if resolved:
        print(f"{len(resolved)} baseline entr(ies) no longer apply -- consider updating.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
