[theme]
base = "dark"
primaryColor = "#f59e0b"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#141417"
textColor = "#fafafa"
font = "sans serif"

[server]
maxUploadSize = 500
headless = true
enableXsrfProtection = true


